# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: $/jeroenvanrensen/blog/models/post/columns.yaml

# Model Class name
modelClass: JeroenvanRensen\Blog\Models\Post

# List Title
title: jeroenvanrensen.blog::lang.controllers.posts.yaml.posts

# Link URL for each record
recordUrl: jeroenvanrensen/blog/posts/update/:id

# Message to display if the list is empty
noRecordsMessage: jeroenvanrensen.blog::lang.controllers.posts.yaml.no_posts_found

# Records to display per page
recordsPerPage: 20

# Display page numbers with pagination, disable to improve performance
showPageNumbers: true

# Displays the list column set up button
showSetup: true

# Displays the sorting link on each column
showSorting: true

# Default sorting column
defaultSort:
    column: published_at
    direction: desc

# Display checkboxes next to each record
showCheckboxes: true

# Filter configuration file
filter: config_filter.yaml

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: jeroenvanrensen.blog::lang.controllers.posts.yaml.search
